version: '3.9'
services:
  social-webhook:
    image: devopsedaya/dcc-slt-socialmedia-webhook-release-v-1.4.001:latest
    container_name: social-webhook-dcc
    hostname: social-webhook-dcc
    logging:
      driver : local
      options:
        max-size: "10M"
    restart: always
    ports:
      - "8005:8005"
    networks:
      - dcc-network
  chat-websocket:
    image: devopsedaya/dcc-slt-socketio-release-v-1.4.002:latest
    container_name: socket-server-dcc
    hostname: socket-server-dcc
    logging:
      driver : local
      options:
        max-size: "10M"
    restart: always
    ports:
      - "8006:8005"
    networks:
      - dcc-network
  chat-api:
    image: devopsedaya/avaya-slt-inaipi-digital-channels-release-v-1.4.014:latest
    container_name: chat-api-server-dcc
    hostname: chat-api-server-dcc
    cpus: 4
    logging:
      driver : local
      options:
        max-size: "10M"
    restart: always
    ports:
      - "8007:8001"
    networks:
      - dcc-network
  uilogs-api:
    image: devopsedaya/dcc-uilogs-release-v-1.1.001:latest
    container_name: uilogs-api-dcc
    hostname: uilogs-api-dcc
    logging:
      driver : local
      options:
        max-size: "10M"
    restart: always
    ports:
      - "8008:8006"
    networks:
      - dcc-network
  file-service:
    image: devopsedaya/fileserver-microservices-release-v-1.1.001:latest
    container_name: file-service-dcc
    hostname: file-service-dcc
    logging:
      driver : local
      options:
        max-size: "10M"
    restart: always
    ports:
      - "8009:8090"
    networks:
      - dcc-network
  dcc-reports:
    image: devopsedaya/dcc-reports-slt-release-v-1.1.002:latest
    container_name: report-api-dcc
    hostname: report-api-dcc
    logging:
      driver : local
      options:
        max-size: "10M"
    restart: always
    ports:
      - "8010:8040"
    networks:
      - dcc-network
  
  dcc-email:
    image: devopsedaya/dcc-slt-email-api-release-v-1.4.008:latest
    container_name: email-api-dcc
    hostname: email-api-dcc
    logging:
      driver : local
      options:
        max-size: "10M"
    restart: always
    ports:
      - "8088:8088"
    networks:
      - dcc-network
  dcc-cron:
    image: devopsedaya/dcc-slt-cron-jobs-release-v-1.4.003:latest
    container_name: cron-jobs-dcc
    hostname: cron-jobs-dcc
    logging:
      driver : local
      options:
        max-size: "10M"
    restart: always
    ports:
      - "8070:8070"
    networks:
      - dcc-network
  user-mmanagement-api:
    image: devopsedaya/dcc-usermanagement-release-v-1.1.001:latest
    container_name: usermodule-api-dcc
    hostname: usermodule-api-dcc
    logging:
      driver : local
      options:
        max-size: "10M"
    restart: always
    ports:
      - "8680:8680"
    networks:
      - dcc-network
  email-analyser:
    image: indukishen/mail-analyser:0.0.5.RELEASE
    container_name: email-analyser-dcc
    hostname: email-analyser-dcc
    logging:
      driver : local
      options:
        max-size: "10M"
    restart: always
    ports:
      - "9005:9005"
    networks:
      - dcc-network
  routing-engine:
    image: praveensk1301/routingrepo201:enginesltv1
    container_name: routing-engine-dcc
    hostname: routing-engine-dcc
    logging:
      driver : local
      options:
        max-size: "10M"
    restart: always
    ports:
      - "9091:9091"
    networks:
      - dcc-network
  queuing-engine:
    image: devopsedaya/dcc-queing-release-v-1.1.001:latest
    container_name: queuing-engine-dcc
    hostname: queuing-engine-dcc
    logging:
      driver : local
      options:
        max-size: "10M"
    restart: always
    ports:
      - "9293:9293"
    networks:
      - dcc-network
  api-gateway:
    image: devopsedaya/dcc-api-gateway-release-v-1.1.001:latest
    container_name: api-gateway-dcc
    hostname: api-gateway-dcc
    logging:
      driver : local
      options:
        max-size: "10M"
    restart: always
    ports:
      - "8762:8762"
    networks:
      - dcc-network
networks:
  dcc-network:
